[package]
name = "notifyd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "3.2.25", features = ["derive"] }
enum-iterator = "1.4.1"
rocket = "=0.5.0-rc.3"
tempdir = "0.3.7"
which = "4.4.0"
